version: '3.8'

services:
  claims-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - backend:/app
    environment:
      - MONGODB_URI=mongodb://claims-mongo:27017/claims-management-system
      - ACCESS_TOKEN_SECRET=hafsfffgg72846285jjjkh54646467hh
    depends_on:
      - claims-mongo

  claims-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"

  claims-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - claims-data:/data/db

volumes:
  claims-data:
  backend:
